language: java
jdk: openjdk12

install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: mvn -e verify

deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: plane-spotting